version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - providersconnect-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  app:
    image: node:latest
    working_dir: /myapp
    command: sh -c "apt-get update && apt-get install -y openssl npm install --include=dev npm prune --omit=dev npx prisma generate npm start"
    volumes:
      - ./:/myapp

volumes:
  providersconnect: